### ISSUE TITLE
The crash of the archer’s attack

### ISSUE THREAD

**Issue by sterh1275** [LiteWolf101/IllagersPlus#1]
I test the mod and spawn archer.
The archer starts the attack and the game crash.
In the test mode, no other mods are installed.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/10/19 2:42 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.item.ItemBow.customizeArrow(Lnet/minecraft/entity/projectile/EntityArrow;)Lnet/minecraft/entity/projectile/EntityArrow;

	at com.litewolf101.objects.entities.EntityArcher.func_82196_d(EntityArcher.java:123)

	at net.minecraft.entity.ai.EntityAIAttackRangedBow.func_75246_d(SourceFile:127)

	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)

	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)

	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)

	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)

	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)

	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)

	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)

	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)

	at com.litewolf101.objects.entities.EntityAbstractIllagerPlus.func_70071_h_(EntityAbstractIllagerPlus.java:30)

	at net.minecraft.world.World.func_72866_a(World.java:1993)

	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)

	at net.minecraft.world.World.func_72870_g(World.java:1955)

	at net.minecraft.world.World.func_72939_s(World.java:1759)

	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)

	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.litewolf101.objects.entities.EntityArcher.func_82196_d(EntityArcher.java:123)
	at net.minecraft.entity.ai.EntityAIAttackRangedBow.func_75246_d(SourceFile:127)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at com.litewolf101.objects.entities.EntityAbstractIllagerPlus.func_70071_h_(EntityAbstractIllagerPlus.java:30)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: illagers_plus:archer (com.litewolf101.objects.entities.EntityArcher)
	Entity ID: 6024
	Entity Name: Archer
	Entity's Exact location: -26.05, 67.00, 260.55
	Entity's Block location: World: (-27,67,260), Chunk: (at 5,4,4 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.04, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Новый мир
	All players: 1 total; [EntityPlayerMP['Silvermist'/877, l='Новый мир', x=-29.20, y=66.77, z=265.70]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 3583651023865437354
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-36,64,252), Chunk: (at 12,4,12 in -3,15; contains blocks -48,0,240 to -33,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1732 game time, 1732 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110301 (now: false), thunder time: 106566 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 231317944 bytes (220 MB) / 494960640 bytes (472 MB) up to 791937024 bytes (755 MB)
	JVM Flags: 5 total; -Xmx768M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version      | Source                        | Signature                                |
	|:--------- |:------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp           | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2775.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2775 | forge-1.12.2-14.23.5.2775.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | illagers_plus | 1.1          | IllagersPlus-1.1.jar          | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Silvermist'/877, l='Новый мир', x=-29.20, y=66.77, z=265.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LiteWolf101** [comment]
Upgrade Forge to version 1.12.2-14.23.5.**2838**
